# Generated by Django 3.0.8 on 2020-07-21 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('lat', models.IntegerField(max_length=255)),
                ('lng', models.IntegerField(max_length=255)),
                ('map_x', models.IntegerField(max_length=255)),
                ('map_y', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('cur_wea', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 7, 21, 7, 35, 20, 592324, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=64)),
                ('user_nick', models.CharField(max_length=64)),
                ('user_pw', models.CharField(max_length=64)),
            ],
        ),
    ]
