# Generated by Django 3.0.3 on 2020-07-21 00:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nalsiwoori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 0, 41, 6, 217001, tzinfo=utc)),
        ),
    ]
