# Generated by Django 3.0.8 on 2020-07-21 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nalsiwoori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 9, 23, 3, 150255, tzinfo=utc)),
        ),
    ]
