# Generated by Django 3.0.3 on 2020-07-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalsiwoori', '0002_selection_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=64)),
                ('user_nick', models.CharField(max_length=64)),
                ('user_pw', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='selection',
            name='pub_date',
        ),
    ]
