# Generated by Django 3.0.3 on 2020-07-21 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nalsiwoori', '0003_auto_20200721_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 2, 44, 51, 725383, tzinfo=utc)),
        ),
    ]
