# Generated by Django 3.0.3 on 2020-07-21 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nalsiwoori', '0004_selection_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='map_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('lat', models.IntegerField(max_length=255)),
                ('lng', models.IntegerField(max_length=255)),
                ('map_x', models.IntegerField(max_length=255)),
                ('map_y', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='selection',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 2, 52, 24, 691301, tzinfo=utc)),
        ),
    ]
