# Generated by Django 3.0.3 on 2020-07-24 02:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('nalsiwoori', '0006_auto_20200723_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 2, 30, 2, 751552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selection',
            name='user_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
