# Generated by Django 3.0.3 on 2020-07-23 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nalsiwoori', '0006_auto_20200723_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 8, 34, 4, 210719, tzinfo=utc)),
        ),
    ]
